vlm:
  model_name: qwen2.5-vl-72b-instruct
  api_key: xxxxx
  base_url: xxxxx
  max_tokens: 1024
  temperature: 0

env:
  serial_no: emulator-5554

enable_log: false

planner:
  enabled: false

operator:
  enabled: true
  name: TrainedOperator
  prompt_config: trained_operator.yaml
  max_pixels: 1048576
  include_device_time: true
  include_tips: true

answer_agent:
  enabled: true
  name: TrainedAnswerAgent
  prompt_config: trained_answer_agent.yaml
  max_pixels: 1048576
  include_device_time: true

reflector:
  enabled: true

trajectory_reflector:
  enabled: true

global_reflector:
  enabled: true

progressor:
  enabled: false

reflect_on_demand: false
logprob_threshold: -0.001
