name: MobileUseMultiAgent

agent:
    name: MobileUseAgent
    args:
      agent_config:

        type: HierarchicalAgent

        vlm:
          model_name: qwen2.5-vl-72b-instruct
          api_key: xxxxx
          base_url: xxxxx
          max_tokens: 1024
          temperature: 0

        enable_hierarchical_planning: true

        planner:
          enabled: false

        operator:
          enabled: true
          name: TrainedOperator
          prompt_config: trained_operator.yaml
          max_pixels: 1048576
          include_device_time: true
          include_tips: true
          include_knowledge: true

        answer_agent:
          enabled: true
          name: TrainedAnswerAgent
          prompt_config: trained_answer_agent.yaml
          max_pixels: 1048576
          include_device_time: true
          include_knowledge: true

        reflector:
          enabled: true

        trajectory_reflector:
          enabled: true

        global_reflector:
          enabled: true

        progressor:
          enabled: false

        task_classifier:
          enabled: true

        task_orchestrator:
          enabled: true

        task_extractor:
          enabled: true

        task_rewriter:
          enabled: true

        reflect_on_demand: false
        logprob_threshold: -0.001



task:
  class: MobileUse_AutoTest
  args:
    save_dir: "./logs/evaluation_mobile_use"
    max_rounds: 25
    request_interval: 3

eval:
  avd_name: Pixel_7_Pro_API_33
  avd_log_dir: ./logs/evaluation
  docker: True
  docker_args:
    image_name: android_eval:latest
    port: 6060
